include_guard(GLOBAL)

if(WIN32 OR (DEFINED COLOR_OUTPUT AND NOT COLOR_OUTPUT))
    set(ColorReset          "")
    set(ColorBold           "")
    set(ColorRed            "")
    set(ColorGreen          "")
    set(ColorYellow         "")
    set(ColorBlue           "")
    set(ColorMagenta        "")
    set(ColorCyan           "")
    set(ColorWhite          "")
    set(ColorBoldRed        "")
    set(ColorBoldGreen      "")
    set(ColorBoldYellow     "")
    set(ColorBoldBlue       "")
    set(ColorBoldMagenta    "")
    set(ColorBoldCyan       "")
    set(ColorBoldWhite      "")
else()
    string(ASCII 27 Esc)
    set(ColorReset          "${Esc}[m")
    set(ColorBold           "${Esc}[1m")
    set(ColorRed            "${Esc}[31m")
    set(ColorGreen          "${Esc}[32m")
    set(ColorYellow         "${Esc}[33m")
    set(ColorBlue           "${Esc}[34m")
    set(ColorMagenta        "${Esc}[35m")
    set(ColorCyan           "${Esc}[36m")
    set(ColorWhite          "${Esc}[37m")
    set(ColorBoldRed        "${Esc}[1;31m")
    set(ColorBoldGreen      "${Esc}[1;32m")
    set(ColorBoldYellow     "${Esc}[1;33m")
    set(ColorBoldBlue       "${Esc}[1;34m")
    set(ColorBoldMagenta    "${Esc}[1;35m")
    set(ColorBoldCyan       "${Esc}[1;36m")
    set(ColorBoldWhite      "${Esc}[1;37m")
endif()
